language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      language: python
      env: TOXENV=py36
install:
  - travis_retry pip install tox codecov
script:
  - tox
after_success:
  - codecov
